### ISSUE TITLE
choice of DEFAULT_FLUSH_INTERVAL for StatsDAggregator

### ISSUE THREAD

**Issue by dbyron0** [DataDog/java-dogstatsd-client#134]
The [aggregation documentation](https://github.com/DataDog/java-dogstatsd-client/blob/de6cc772301d0637abea63ec91f4a152e9baea64/README.md#aggregation) says:

> ...so long as the flush interval configured configured on the client side is smaller than said flush interval on the server side there should no loss in resolution

But from what I can tell, the default values for the client [here in java-dogstatsd-client](https://github.com/DataDog/java-dogstatsd-client/blob/de6cc772301d0637abea63ec91f4a152e9baea64/src/main/java/com/timgroup/statsd/StatsDAggregator.java#L18) of 3 seconds is quite a bit bigger than the default flush interval in [the datadog agent](https://github.com/DataDog/datadog-agent/blob/53c30898bac9d0a91c980d189171bd1767793ab1/pkg/config/config.go#L349) of 100 milliseconds.  From what I can see the default in the datadog agent hasn't changed in some time, if ever.

Does it make sense to choose a smaller number here to make the defaults "safe"?

**Comment by truthbk** [comment]
@dbyron0 thank you for showing your concern with regards to the aggregation feature and its implementation and for digging deeper into it.

The value we're really interested in for the dogstatsd server is the aggregation granularity of buckets which is defined here: https://github.com/DataDog/datadog-agent/blob/master/pkg/aggregator/aggregator.go#L32 and has a hard-coded value of 10s; that's the size of the aggregation buckets. The packet buffer flush period of 100ms has no impact in the actual aggregation of contexts. And as you very well pointed it was important to not be overly aggressive and define conservative sane values which is why we went for a 3s flush interval in the client. 

I hope this clarifies things. I am going to go ahead and close this issue, but please feel free to reach out if anything remains unclear. Once again, thank you for reaching out! 🙇

**Comment by dbyron0** [comment]
Thanks for clarifying.  This would be helpful info to have directly in the readme.  I'll try to carve out some time to make a PR, but wouldn't be surprised if someone else beats me to it.

FWIW, the code you linked to wasn't super clear to me at first glance either...The line above has a comment about a 15 second flush interval, and it takes some digging to see that the units of `bucketSize` are seconds.  Probably the key thing is that any kind of flush interval in the agent sounds like it's not relevant...and it's the aggregation buckets that matter.  I bet that's something you (or someone else) can explain way better than me.
