### ISSUE TITLE
Once datadog agent crashed and redeployed the metrics are not shown in Datadog dashboard

### ISSUE THREAD

**Issue by dmitriymermelstein** [DataDog/java-dogstatsd-client#192]
I'm using the java dogstatsd client for sending metrics. The issue started when the Datadog agent crashed. Once it's redeployed again the metrics are stopped to be shown in the Datadog dashboard. I see my log trace after calling by statsd client but the metrics are not shown in the datadog dashboard. Is there a reconnection issue between java dogstatsd client and datadog agent preventing the metric publishing?

The Java application uses: Gradle 6.3 springboot': '2.3.0.RELEASE java-dogstatsd-client 3.0.0

**Comment by vickenty** [comment]
Hi @dmitriymermelstein,

Sorry to hear you are missing metrics. It does seem like a problem with reconnection. Could you please provide some details about your environment:

1. What operating system are you using?
1. Are you using UDP or unix sockets (UDS) to communicate with the agent?
2. Is the agent or application deployed in the container? If yes, what kind of containers?
3. Do you use an error handler with the statsd client? If yes, did you get any errors?
4. Can you see other metrics, such as host metrics, after the agent restart in the app?

I don't know if this applies to your situation, but one possible reason for this issue is when using containers and the dogstatsd unix socket volume uses full path to the file. Due to how container volumes work, client does not see the new socket after the agent restart, and  can not communicate with the new agent process. The solution in this case is to use a directory volume instead of a full path (e.g. `path:/var/run/datadog` instead of `path:/var/run/datadog/dsd.socket`).

**Comment by dmitriymermelstein** [comment]
Hi @vickenty,

Thank you for your response.

Please see below the answers to your questions.

1. OS - Linux.
2. Used UDP by default.
3. Amazon EKS.
4. Yes, should be printed an error. The errors are not printed.
5. No, I also do not see any datadog.dogstatsd.client.* metrics once the agent crashed and redeployed.

How can I initially make sure that metrics are sent by dogstatsd client?

This my code:
`StatsDClient statsd = new NonBlockingStatsDClientBuilder()
                .prefix("statsd")
                .hostname(statsdHost)
                .port(8125)
                .errorHandler(e -> System.out.println("StatsDClient error: " + e.getMessage()))
                .build();
statsd.count("app.datadog.metrics.test", 1);
`

**Comment by vickenty** [comment]
Thank you for providing this extra information.

Just in case, what is the value of `statsdHost` in your code? If the agent pod is restarted, it's IP address will change, so the traffic may end up going to the wrong destination (although it shouldn't matter if the dogstatsd traffic goes via the [host port](https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#setup)).

But the fact that you don't see not only statsd metrics, but also host metrics after the agent restarts, suggests that the issue may be in the connection between the agent and Datadog. If it is the case, please check out our [agent troubleshooting](https://docs.datadoghq.com/agent/troubleshooting/) page, and feel free to contact our [support](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7) if you require further assistance.

**Comment by vickenty** [comment]
I'm closing this issue for now, feel free to re-open if you have further questions!
