### ISSUE TITLE
Snyk Issue with jnr-posix

### ISSUE THREAD

**Issue by prathyush90** [DataDog/java-dogstatsd-client#252]
In my organization, we use Snyk as a security measure and Datadog for collecting events. We have encountered a Snyk issue due to the jnr-posix library used by the java-dogstatsd-client. The details of the issue can be found in the following link:

https://security.snyk.io/vuln/SNYK-JAVA-COMGITHUBJNR-1570422

We have attempted to upgrade jnr-posix(tried 3.1.19 and 18), but the issue persists. Could you please assist us in finding a solution to this problem? If no solution exists, Can i exclude this module in dependency? Does datadog depend on this

**Comment by vickenty** [comment]
Hi! Thank you for using Datadog.

java-dogstatsd-client is not affected by this vulnerability, because they never call the vulnerable `posix_spawn` function.

If you are using Java 8 or later, you can use a newer version of jnr-unixsocket in your build by following the instructions [here](https://github.com/DataDog/java-dogstatsd-client/blob/master/DEPS.md). Or, if you are not using unix sockets at all, the same page has instructions on removing the dependency entirely. Both approaches should help to avoid Snyk warning.

**Comment by prathyush90** [comment]
Hi @vickenty I tried newer version of jnr-unixsocket it didn't work but when i removed it completely it worked. 

I have a query regarding unix sockets. In our code we donot use unix sockets and for Datadog its using DatadogMeterRegistry class which in turn is calling HttpUrlConnectionSender. Is it safe for me to remove the socket dependency?

**Comment by vickenty** [comment]
`DatadogMeterRegistry` class comes from [micrometer](https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java), which is a different library and not related to java-dogstatsd-client in any way.

Please see if your code is using `NonBlockingStatsDClientBuilder` class, which is the entry point for java-dogstatsd-client. It can be configured to use unix sockets by calling `.port(0)` method on the builder, or by setting one of `DD_DOGSTATSD_PORT` or `DD_DOGSTATSD_URL` environment variables. If the port value is zero, or the URL starts with `unix://` then you are using unix sockets.

If there is no places that use `NonBlockingStatsDClientBuilder`, then it is likely that you are not using java-dogstatsd-client in your application and could perhaps remove the entire dependency.

**Comment by leafknode** [comment]
I wanted to add my 2 cents here... I also just encountered this issue today (also use Snyk) and doing a little more research here, the [jnr-posix library license](https://github.com/jnr/jnr-posix/blob/master/LICENSE.txt) is `EPL` or `GPL` or `LGPL`.  Meaning, you can pick your flavor depending on your needs.  And, while the EPL is a copyleft license, it's not as restrictive as GPL or LGPG in that you can use the code (without worry of open sourcing your own code) as long as you aren't a Contributor.  And, a Contributor is defined as:

```
  "Contribution" means:

    a) in the case of the initial Contributor, the initial content
       Distributed under this Agreement, and

    b) in the case of each subsequent Contributor:
       i) changes to the Program, and
       ii) additions to the Program;
    where such changes and/or additions to the Program originate from
    and are Distributed by that particular Contributor. A Contribution
    "originates" from a Contributor if it was added to the Program by
    such Contributor itself or anyone acting on such Contributor's behalf.
    Contributions do not include changes or additions to the Program that
    are not Modified Works.
```

Additional validation and summarization from from [fossa.com](https://fossa.com/blog/open-source-software-licenses-101-eclipse-public-license/):

```
Under the EPL, if you simply use — rather than modify — an EPL-licensed component and keep it in a separate file, that would not constitute a derivative work, and you would not be required to make available your source code. With the GPLs, however, any use (modified or not) of the licensed code would create a derivative work.
```

`tl;dr`: If I'm understanding all of this correctly (I'm no Lawyer), you're safe to use EPL licensed libraries at an organization assuming you don't modify or make any additions to the library.

With all of this said, if would behoove you guys to just replace this library altogether so that future users of the [java-dogstatsd-client](https://github.com/DataDog/java-dogstatsd-client) don't experience this same issue.
